name: starbucks
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.2
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.3
  share_plus: ^9.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  get_storage: ^2.1.1
  webview_flutter: ^4.8.0
  screenshot: ^3.0.0
  flutter_zoom_drawer: ^3.2.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  flutter_device_id: ^1.0.1
  app_tracking_transparency: ^2.0.5
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

  #  facebook ads
  facebook_app_events: ^0.19.2
  easy_ads_flutter: ^2.4.4
  # APPLOVIN ADS STEP 1
  applovin_max: ^3.10.1

dependency_overrides:
  easy_audience_network:
    git:
      url: https://github.com/kaushikgodhani/audience_network_flutter.git
      ref: c67f254ea8d3006024daecd26776ad55522eaf05


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.jpg"
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/useAppImages/
    - assets/database/
    - assets/lottie/

  fonts:
    - family: B
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: R
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: EB
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: M
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: SB
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
